ARG centos=8.1.1911
FROM aursu/rpmbuild:${centos}-build

USER root
RUN yum -y install \
        gtest-devel \
    && yum clean all && rm -rf /var/cache/yum

# RUN yum -y --enablerepo=bintray-custom install \
#    && yum clean all && rm -rf /var/cache/yum
